/**
 * A `bun build --compile` binary cannot read sibling files at runtime: `__dirname` retains the
 * *build* machine's path, `import.meta.dir` becomes the virtual `/$bunfs/root`, and `/$bunfs` is
 * opaque — `existsSync` returns false for every path including its own root. Hence constants.
 *
 * Everything embedded here is redistributed, by the binary and by every `--output` file. A new
 * asset needs its licence added to THIRD-PARTY-NOTICES.md before it ships.
 */

import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';

const require = createRequire(import.meta.url);
const repositoryRoot = join(import.meta.dir, '..');

/**
 * Resolved *through* rehype-katex, never from the top level: rehype-katex@7 renders the math HTML
 * with whatever katex copy it resolves, and KaTeX 0.18 renamed the layout classes
 * (`base`/`strut`/`sizing` -> `katex-base`/...). 0.16-rendered HTML with 0.18 CSS builds green,
 * tests green, and renders every superscript and fraction at the wrong size.
 */
function resolveKatexDistribution(): { distributionPath: string; version: string } {
  const rehypeKatexRequire = createRequire(require.resolve('rehype-katex'));
  const packageJsonPath = rehypeKatexRequire.resolve('katex/package.json');
  const version = JSON.parse(readFileSync(packageJsonPath, 'utf8')).version as string;

  if (!version.startsWith('0.16.')) {
    throw new Error(
      `rehype-katex resolved katex@${version}, but only the 0.16 line matches the CSS class ` +
        'names this project embeds. Pin katex to 0.16.x.',
    );
  }

  return { distributionPath: join(dirname(packageJsonPath), 'dist'), version };
}

const { distributionPath: katexDistribution, version: katexVersion } = resolveKatexDistribution();

/**
 * `dist/mermaid.min.js`, never the package entry point: on a `file://` URL the browser blocks every
 * static and dynamic `import()`, so mermaid's ESM entry (38 dynamic imports) cannot load. That IIFE
 * build is undocumented, reachable only through the package's `"./*"` catch-all export, and v10
 * dropped it once already (mermaid-js/mermaid#4279, restored by #4281) —
 * `tests/mermaid-bundle.test.ts` guards its shape against a routine version bump.
 */
function resolveMermaidBundle(): { scriptPath: string; version: string } {
  const packageJsonPath = require.resolve('mermaid/package.json');
  const version = JSON.parse(readFileSync(packageJsonPath, 'utf8')).version as string;

  return { scriptPath: join(dirname(packageJsonPath), 'dist', 'mermaid.min.js'), version };
}

const { scriptPath: mermaidScriptPath, version: mermaidVersion } = resolveMermaidBundle();

const githubMarkdownCssDirectory = dirname(require.resolve('github-markdown-css/package.json'));

/**
 * Browsers request only the first supported format, so the woff and truetype URLs are never
 * fetched — keeping them would mean shipping 40 more font files or emitting dead references.
 */
function keepWoff2SourcesOnly(css: string): string {
  return css.replace(/src:([^;}]+)/g, (match, sources: string) => {
    const woff2Source = sources
      .split(',')
      .map((source) => source.trim())
      .find((source) => source.includes('.woff2'));

    return woff2Source ? `src:${woff2Source}` : match;
  });
}

function readText(path: string): string {
  return readFileSync(path, 'utf8');
}

function readBase64(path: string): string {
  return readFileSync(path).toString('base64');
}

const matVersion = JSON.parse(readText(join(repositoryRoot, 'package.json'))).version as string;

const mermaidScript = readText(mermaidScriptPath);

const githubMarkdownCss = {
  auto: readText(join(githubMarkdownCssDirectory, 'github-markdown.css')),
  light: readText(join(githubMarkdownCssDirectory, 'github-markdown-light.css')),
  dark: readText(join(githubMarkdownCssDirectory, 'github-markdown-dark.css')),
};

const katexCss = keepWoff2SourcesOnly(readText(join(katexDistribution, 'katex.min.css')));

const chromeCss = readText(join(repositoryRoot, 'src', 'html', 'chrome.css'));

const katexFontsDirectory = join(katexDistribution, 'fonts');
const katexFonts = readdirSync(katexFontsDirectory)
  .filter((fileName) => fileName.endsWith('.woff2'))
  .sort()
  .map((fileName) => ({ fileName, base64: readBase64(join(katexFontsDirectory, fileName)) }));

const onigurumaWasmBase64 = readBase64(
  join(dirname(require.resolve('vscode-oniguruma/package.json')), 'release', 'onig.wasm'),
);

const generated = `// GENERATED by scripts/embed.ts — do not edit, do not commit.
// Run \`bun run build:assets\` to regenerate.
//
// katex resolved through rehype-katex: ${katexVersion}
// mermaid: ${mermaidVersion} (dist/mermaid.min.js)

export const MAT_VERSION = ${JSON.stringify(matVersion)};

export type ThemeName = 'auto' | 'light' | 'dark';

export const MERMAID_SCRIPT = ${JSON.stringify(mermaidScript)};

export const GITHUB_MARKDOWN_CSS: Readonly<Record<ThemeName, string>> = {
  auto: ${JSON.stringify(githubMarkdownCss.auto)},
  light: ${JSON.stringify(githubMarkdownCss.light)},
  dark: ${JSON.stringify(githubMarkdownCss.dark)},
};

export const CHROME_CSS = ${JSON.stringify(chromeCss)};

/** Still contains \`url(fonts/NAME.woff2)\` references; the emitter rewrites them. */
export const KATEX_CSS = ${JSON.stringify(katexCss)};

export const KATEX_VERSION = ${JSON.stringify(katexVersion)};

export const KATEX_FONTS: ReadonlyArray<{ fileName: string; base64: string }> = [
${katexFonts.map((font) => `  { fileName: ${JSON.stringify(font.fileName)}, base64: ${JSON.stringify(font.base64)} },`).join('\n')}
];

export const ONIGURUMA_WASM_BASE64 = ${JSON.stringify(onigurumaWasmBase64)};
`;

const outputDirectory = join(repositoryRoot, 'src', 'generated');
mkdirSync(outputDirectory, { recursive: true });
writeFileSync(join(outputDirectory, 'assets.ts'), generated);

const summary = [
  `mat            ${matVersion}`,
  `katex          ${katexVersion} (resolved through rehype-katex)`,
  `mermaid        ${mermaidVersion} (${mermaidScript.length.toLocaleString('en-US')} bytes)`,
  `markdown css   ${Object.values(githubMarkdownCss)
    .reduce((total, css) => total + css.length, 0)
    .toLocaleString('en-US')} bytes across 3 themes`,
  `katex css      ${katexCss.length.toLocaleString('en-US')} bytes`,
  `katex fonts    ${katexFonts.length} woff2`,
  `oniguruma      ${onigurumaWasmBase64.length.toLocaleString('en-US')} bytes base64`,
  `-> src/generated/assets.ts (${generated.length.toLocaleString('en-US')} bytes)`,
].join('\n');

process.stdout.write(`${summary}\n`);
