/**
 * Importing `all` from `@wooorm/starry-night` pulls in 19 MB of grammar objects: measured 5.7 s
 * from `node_modules`, ~500 ms from a compiled binary, plus ~5 s for `createStarryNight(all)` to
 * register every scope. The emitted per-grammar thunks cost 2 ms to load the index, 1 ms per
 * grammar and 8 ms to build the highlighter.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { all } from '@wooorm/starry-night';

const repositoryRoot = join(import.meta.dir, '..');

/**
 * Must mirror the registration order inside `createStarryNight`: later grammars overwrite earlier
 * ones, and `flagToScope` consults names, then extensions, then extensions-with-dot.
 */
function tableOf(pick: (grammar: (typeof all)[number]) => readonly string[] | undefined) {
  const table = new Map<string, string>();

  for (const grammar of all) {
    for (const key of pick(grammar) ?? []) {
      table.set(key, grammar.scopeName);
    }
  }

  return [...table].sort(([left], [right]) => (left < right ? -1 : 1));
}

function renderTable(name: string, entries: ReadonlyArray<[string, string]>): string {
  const body = entries
    .map(([key, scope]) => `  ${JSON.stringify(key)}: ${JSON.stringify(scope)},`)
    .join('\n');

  return `export const ${name}: Readonly<Record<string, string>> = {\n${body}\n};`;
}

const scopes = [...all].map((grammar) => grammar.scopeName).sort();

const modules = scopes
  .map((scope) => `  ${JSON.stringify(scope)}: () => import('@wooorm/starry-night/${scope}'),`)
  .join('\n');

const names = tableOf((grammar) => grammar.names);
const extensions = tableOf((grammar) => grammar.extensions);
const extensionsWithDot = tableOf((grammar) => grammar.extensionsWithDot);

const generated = `// GENERATED by scripts/embed-grammars.ts — do not edit, do not commit.
// Run \`bun run build:assets\` to regenerate.
//
// ${scopes.length} grammars from @wooorm/starry-night.

import type { Grammar } from '@wooorm/starry-night';

/** The specifiers must stay literal: the bundler cannot resolve a computed one. */
export const GRAMMAR_MODULES: Readonly<Record<string, () => Promise<{ default: Grammar }>>> = {
${modules}
};

${renderTable('SCOPE_BY_NAME', names)}

${renderTable('SCOPE_BY_EXTENSION', extensions)}

${renderTable('SCOPE_BY_EXTENSION_WITH_DOT', extensionsWithDot)}
`;

const outputDirectory = join(repositoryRoot, 'src', 'generated');
mkdirSync(outputDirectory, { recursive: true });
writeFileSync(join(outputDirectory, 'grammars.ts'), generated);

const summary = [
  `grammars       ${scopes.length}`,
  `names          ${names.length}`,
  `extensions     ${extensions.length} plus ${extensionsWithDot.length} with dot`,
  `-> src/generated/grammars.ts (${generated.length.toLocaleString('en-US')} bytes)`,
].join('\n');

process.stdout.write(`${summary}\n`);
