/**
 * A formula rather than a cask: casks are the one installation path that applies
 * `com.apple.quarantine`, `--no-quarantine` is deprecated since Homebrew 5.0, and from 2026-09-01
 * Homebrew drops casks that fail Gatekeeper. Formulae are never quarantined.
 */

import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const REPOSITORY = 'BoundfoxStudios/mat';

interface Asset {
  readonly fileName: string;
  readonly platform: 'macos' | 'linux';
  readonly architecture: 'arm' | 'intel';
}

const ASSETS: readonly Asset[] = [
  { fileName: 'mat-darwin-arm64', platform: 'macos', architecture: 'arm' },
  { fileName: 'mat-linux-arm64', platform: 'linux', architecture: 'arm' },
  { fileName: 'mat-linux-x64', platform: 'linux', architecture: 'intel' },
];

function argument(name: string): string {
  const flag = `--${name}`;
  const index = process.argv.indexOf(flag);
  const value = index === -1 ? undefined : process.argv[index + 1];

  // A value that looks like a flag means the real one was left out; swallowing it would generate
  // a formula for a version nobody asked for.
  if (value === undefined || value.startsWith('--')) {
    throw new Error(`missing value for ${flag}`);
  }

  return value;
}

function sha256Of(path: string): string {
  return createHash('sha256').update(readFileSync(path)).digest('hex');
}

function platformBlock(
  platform: Asset['platform'],
  version: string,
  digests: ReadonlyMap<string, string>,
): string {
  const blocks = ASSETS.filter((asset) => asset.platform === platform).map((asset) => {
    const digest = digests.get(asset.fileName);

    if (!digest) {
      throw new Error(`no binary for ${asset.fileName}`);
    }

    return [
      `    on_${asset.architecture} do`,
      `      url "https://github.com/${REPOSITORY}/releases/download/v${version}/${asset.fileName}"`,
      `      sha256 "${digest}"`,
      '    end',
    ].join('\n');
  });

  return [`  on_${platform} do`, ...blocks, '  end'].join('\n');
}

/**
 * The formula states no `version` — `brew audit --strict` rejects it as redundant with the one
 * Homebrew scans from the `/download/vX.Y.Z/` URL segment. That parser only recognises
 * `\d+(\.\d+)+`: given a prerelease tag it falls back to the trailing digits of the *file name*,
 * releasing `mat-darwin-arm64` as version "64" — which is what `brew upgrade` compares.
 */
const RELEASE_VERSION = /^\d+\.\d+\.\d+$/;

const version = argument('version').replace(/^v/, '');
const binariesDirectory = argument('binaries');

if (!RELEASE_VERSION.test(version)) {
  throw new Error(
    `--version must be X.Y.Z, got "${version}". Homebrew cannot read a prerelease version out of ` +
      'the download URL, and the formula states none.',
  );
}

const packageVersion = (
  JSON.parse(readFileSync(join(import.meta.dir, '..', 'package.json'), 'utf8')) as {
    version: string;
  }
).version;

if (packageVersion !== version) {
  throw new Error(
    `version mismatch: --version is \`${version}\`, package.json is \`${packageVersion}\`. ` +
      'The binaries report the package.json version, so the tag has to match it.',
  );
}

const digests = new Map(
  ASSETS.map((asset) => [asset.fileName, sha256Of(join(binariesDirectory, asset.fileName))]),
);

/**
 * Attached as resources so `brew install` puts them next to the binary.
 *
 * Several of the licences mat redistributes require their notice to accompany the distribution,
 * and a Homebrew install downloads one binary and nothing else.
 */
const NOTICES: ReadonlyArray<{ fileName: string; repositoryPath: string }> = [
  { fileName: 'THIRD-PARTY-NOTICES.md', repositoryPath: 'THIRD-PARTY-NOTICES.md' },
  {
    fileName: 'starry-night-grammars-notice.txt',
    repositoryPath: join('third-party', 'starry-night-grammars-notice.txt'),
  },
  {
    fileName: 'vscode-oniguruma-notice.txt',
    repositoryPath: join('third-party', 'vscode-oniguruma-notice.txt'),
  },
];

const noticeBlocks = NOTICES.map((notice) =>
  [
    `  resource "${notice.fileName}" do`,
    `    url "https://github.com/${REPOSITORY}/releases/download/v${version}/${notice.fileName}"`,
    `    sha256 "${sha256Of(join(import.meta.dir, '..', notice.repositoryPath))}"`,
    '  end',
  ].join('\n'),
).join('\n\n');

// One `install` for all assets: only one of them is ever downloaded.
const formula = `# Generated by scripts/release.ts. Do not edit by hand.
class Mat < Formula
  desc "Preview a Markdown file in your browser, the way GitHub renders it"
  homepage "https://github.com/${REPOSITORY}"
  license "MIT"

${platformBlock('macos', version, digests)}

${platformBlock('linux', version, digests)}

${noticeBlocks}

  def install
    bin.install Dir["mat-*"].first => "mat"

${NOTICES.map((notice) => `    resource("${notice.fileName}").stage { doc.install "${notice.fileName}" }`).join('\n')}
  end

  test do
    (testpath/"note.md").write("# Hallo\\n")
    assert_match "mat #{version}", shell_output("#{bin}/mat --version")
    assert_match "<h1 id=\\"hallo\\">",
                 shell_output("#{bin}/mat #{testpath}/note.md --output -")
  end
end
`;

const formulaDirectory = join(import.meta.dir, '..', 'Formula');
mkdirSync(formulaDirectory, { recursive: true });
writeFileSync(join(formulaDirectory, 'mat.rb'), formula);

const summary = [
  `version  ${version}`,
  ...ASSETS.map((asset) => `${asset.fileName.padEnd(20)} ${digests.get(asset.fileName)}`),
  '-> Formula/mat.rb',
].join('\n');

process.stdout.write(`${summary}\n`);
